#!/usr/bin/env ruby
# frozen_string_literal: false

public

require 'optparse'
require 'open3'

begin
  require 'highline'
  require 'colored'
rescue LoadError
  puts <<~XXX
    To run this utility:
      gem install 'highline'
      gem install 'colored'
  XXX
  exit(1)
end

class Konnect
  attr_accessor :app, :rack, :command, :service_filter, :op, :any, :exclude_entrypoint_env, :use_xterm

  CONVOX_BIN = `which convox`.strip

  def initialize
    @rack = `convox switch`.strip
    @app = nil
    @command = 'bash'
    @service_filter = /.*/
    @any = false
    @exclude_entrypoint_env = true
    @use_xterm = false
  end

  def konnect_error(message)
    puts("#{op.banner}.\n\nError: #{message}")
    exit 1
  end

  def go
    parse_opts

    check_for_convox

    ids_to_names = filtered_id_to_name_map

    all_names_the_same = ids_to_names.values.uniq.size.eql?(1)

    instance_id = if all_names_the_same && any
                    ids_to_names.keys.sample
                  else
                    choose_service(ids_to_names)
                  end

    cmd = "#{CONVOX_BIN} exec --rack #{rack} --app #{app} #{instance_id} " # keep the space on the end

    cmd += "TERM=xterm LINES=#{screen_rows} ROWS=#{screen_rows} COLUMNS=#{screen_columns} " if use_xterm

    cmd = if exclude_entrypoint_env
            cmd + command
          else
            cmd + "bin/entrypoint.sh #{command}"
          end

    info "About to run:\n\t#{cmd}"
    exec cmd
  end

  def parse_opts
    self.op = OptionParser.new do |opts|
      opts.banner = <<~BAN

        A wrapper for 'convox exec' that takes a service name (or part of one) instead of the process id, and automatically runs entrypoint-env.sh before running the command you provide.

        If you provide no command to run, it runs 'bash'.

        Ex:
              konnect
                # menu of all containers for app 'kraken' in current stack
                # you will be ssh'd into the container you pick

              konnect -s billing -a kraken
                # run 'bin/entrypoint-env.sh bash' on wb-billing service
                # on the current app and rack

              konnect -s billing -a kraken -c "bin/rails c"
                # run 'bin/entrypoint-env.sh bin/rails c' on wb-billing service
                # on the current app and rack

              konnect -r staging -a kraken -s billing -c "bin/rails c"
                # run the command on the specified rack and app

              konnect -r staging -a kraken -s billing --any
                # run the command on any instance that matches the filter

      BAN

      opts.separator ''
      opts.separator 'Specific options:'

      opts.on('-z', '--debug', 'Optional: load pry') do |_x|
        require 'pry'
      end

      opts.on('-c', '--rack=R', "Optional, the command, default: 'bash'") do |x|
        self.command = x
      end

      opts.on('-r', '--rack=R', 'Optional, the convox rack') do |x|
        self.rack = x
      end

      opts.on('-e', '--exclude-env-entrypont', 'Optional, do not wrap the command with the entrypoint-env script') do
        self.exclude_entrypoint_env = true
      end

      opts.on('-a', '--app=A', 'Optional, the convox app.') do |x|
        self.app = x
      end

      opts.on('-s', '--service=S', 'Required: which service (a regex)') do |x|
        self.service_filter = /#{x}/
      end

      opts.on('-n', '--any', 'Optional, connect to any matching instance.') do |x|
        self.any = x
      end
    end

    op.parse!(ARGV)

    if app.nil?
      info "--app not provided, using 'kraken'"
      self.app = 'kraken'
    end
  end

  def check_for_convox
    konnect_error "Command 'convox' was not found in your PATH" if CONVOX_BIN.to_s.empty?
  end

  def id_name_map
    cmd = "#{CONVOX_BIN} ps --rack #{rack} --app #{app}"
    info cmd
    stdout, stderr, status = Open3.capture3(cmd)
    konnect_error(stderr) if status.exitstatus.eql?(1)

    lines = stdout.lines[1..-1]

    # Create a map of instance id to instance name
    Hash[lines.map do |line|
      line.split(/\s{2,}/).first(2)
    end]
  end

  def filtered_id_to_name_map
    services_map = id_name_map
    services_map.delete_if { |k, v| "#{k}-#{v}" !~ service_filter }
    konnect_error "No services matched #{service_filter}" if services_map.empty?
    services_map
  end

  def choose_service(service_map)
    return service_map.keys.first if service_map.size.eql?(1)

    puts "\n"
    choice = nil
    cli.choose do |menu|
      menu.prompt = "\nWhich service?".yellow
      service_map.each do |id, name|
        menu.choice("#{name} #{id}") { choice = id }
      end
      menu.choice('quit') { exit 0 }
    end
    choice
  end

  def info(msg)
    warn msg.blue
  end

  def screen_rows
    TermInfo.screen_size.first
  end

  def screen_columns
    TermInfo.screen_size.last
  end

  def cli
    @_cli = HighLine.new
  end
end

Konnect.new.go
