#!/usr/bin/env ruby
# frozen_string_literal: false

require "#{File.expand_path(__dir__)}/includes/op_base.rb"

# CLI script which will start local convox app
class StartConvoxApp < OpBase
  attr_accessor :convox_app_path

  def go
    self.convox_app_path = Dir.getwd

    unless File.exist?('./convox.local.yml')
      puts "Could not find file 'convox.local.yml'.".red
      exit
    end

    exec_ic_command 'DEBUG_CONVOX=true convox start -m convox.local.yml'
  end
end

StartConvoxApp.new.go
